### ISSUE TITLE
Creating a recipe

### ISSUE THREAD

**Issue by B1nTree** [ChuckHeintzelman/laravel-recipes#9]
I don't see any documentation to create your own recipes yet. I have one to contribute, could I get some insight? Thanks!

**Comment by ChuckHeintzelman** [comment]
Yeah, I've been a bit of a slacker there and it's been Sooo long, I'm trying to remember.

Here's what you do.

First, fork and install laravel-recipes locally and setup the database

Then create a new .md file in the appropriate docs/recipes/SUBDIR

make sure the document has the top section, without the Id: or Position: labels.

Then run artisan recipe:scan to see there's no big errors (you'll get a warning that it doesn't exist).

If there's no problem run artisan recipe:sync to see if it adds it locally to your db. If there's an error run recipe:sync again.

When all done, update your fork with the new md you created and create a pull request.


Yeah, lots of steps.
